/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;


import javax.swing.JOptionPane;
import Control.ControleConta;
import Control.ControleEntrada;
import Control.ControleSaida;
import Model.Conta;
import Model.Entrada;
import Model.Saida;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author Aluno
 */
public class tela1 extends javax.swing.JFrame {
    
    ControleConta controleConta = new ControleConta();
    ControleEntrada controleEntrada = new ControleEntrada();
    ControleSaida controleSaida = new ControleSaida();
    
    public void adicionaLinhaTabelaContas(){
        DefaultTableModel model = (DefaultTableModel) jTableContas.getModel();
        Object rowData[] = new Object[3];
        model.setRowCount(0);
        List<Conta> contas = controleConta.BuscarContas();
        for(int i = model.getRowCount(); i<contas.size() ;i++){
            rowData[0] = contas.get(i).getId();
            rowData[1] = contas.get(i).getNome();
            rowData[2] = contas.get(i).getSaldo();
            model.addRow(rowData);
        }
    }
    
    public void adicionaLinhaTabelaEntradas(){
        DefaultTableModel model = (DefaultTableModel) jTableEntradas.getModel();
       
        Object rowData[] = new Object[4];
        
        List<Entrada> entradas = controleEntrada.BuscarEntradas();
        for(int i = model.getRowCount(); i<entradas.size() ;i++){
            rowData[0] = entradas.get(i).getId();
            rowData[1] = entradas.get(i).getDescricao();
            rowData[2] = entradas.get(i).getData();
            rowData[3] = entradas.get(i).getValor();
            model.addRow(rowData);
        }
    }
    
    public void adicionaLinhaTabelaSaidas(){
        DefaultTableModel model = (DefaultTableModel) jTableSaidas.getModel();
        Object rowData[] = new Object[3];

        List<Saida> saidas = controleSaida.BuscarSaidas();
        for(int i = model.getRowCount(); i<saidas.size() ;i++){
            rowData[0] = saidas.get(i).getId();
            rowData[1] = saidas.get(i).getDescricao();
            rowData[2] = saidas.get(i).getData();
            rowData[3] = saidas.get(i).getValor();
            model.addRow(rowData);
        }
    }
    

    /**
     * Creates new form tela1
     */
    public tela1() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldValorEntrada = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxContaEntrada = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jButtonConfirmarEntrada = new javax.swing.JButton();
        jTextFieldDataEntrada = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEntradas = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldValorSaida = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jComboBoxContaSaida = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jButtonConfirmarSaida = new javax.swing.JButton();
        jTextFieldDataSaida = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableSaidas = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jTextFieldNomeConta = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jButtonConfirmarConta = new javax.swing.JButton();
        jTextFieldValorInicial = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableContas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTabbedPane1.setMinimumSize(new java.awt.Dimension(800, 600));
        jTabbedPane1.setName(""); // NOI18N

        jLabel1.setText("Valor");

        jLabel2.setText("Data");

        jComboBoxContaEntrada.setModel(jComboBoxContaEntrada.getModel());
        jComboBoxContaEntrada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxContaEntradaMouseClicked(evt);
            }
        });

        jLabel3.setText("Conta");

        jButtonConfirmarEntrada.setText("Confirmar");
        jButtonConfirmarEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarEntradaActionPerformed(evt);
            }
        });

        jTableEntradas.setBackground(new java.awt.Color(51, 255, 51));
        jTableEntradas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Conta", "Data", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableEntradas.setGridColor(new java.awt.Color(153, 153, 153));
        jTableEntradas.setSelectionBackground(new java.awt.Color(51, 102, 255));
        jScrollPane1.setViewportView(jTableEntradas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldValorEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldDataEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jComboBoxContaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonConfirmarEntrada))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldValorEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxContaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonConfirmarEntrada)
                    .addComponent(jTextFieldDataEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Entradas", jPanel1);

        jLabel13.setText("Valor");

        jLabel14.setText("Data");

        jComboBoxContaSaida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxContaSaidaMouseClicked(evt);
            }
        });

        jLabel15.setText("Conta");

        jButtonConfirmarSaida.setText("Confirmar");
        jButtonConfirmarSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarSaidaActionPerformed(evt);
            }
        });

        jTableSaidas.setBackground(new java.awt.Color(255, 0, 0));
        jTableSaidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Conta", "Data", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTableSaidas);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldValorSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jTextFieldDataSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jComboBoxContaSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonConfirmarSaida))))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldValorSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxContaSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonConfirmarSaida)
                    .addComponent(jTextFieldDataSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Saídas", jPanel2);

        jLabel18.setText("Nome");

        jLabel19.setText("Valor Inicial");

        jButtonConfirmarConta.setText("Confirmar");
        jButtonConfirmarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarContaActionPerformed(evt);
            }
        });

        jTableContas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Conta", "Saldo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableContas);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNomeConta, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jTextFieldValorInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonConfirmarConta))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNomeConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonConfirmarConta)
                    .addComponent(jTextFieldValorInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Contas", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConfirmarEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarEntradaActionPerformed
                
        double validaValorEntrada = Double.parseDouble(jTextFieldValorEntrada.getText());
        
        if(jTextFieldValorEntrada.getText().equals("") || validaValorEntrada <= 0){
            JOptionPane.showMessageDialog(this,
                    "Valor de entrada invalido!" ,
                    "Entrada",
                    JOptionPane.ERROR_MESSAGE);
        }else if(jTextFieldDataEntrada.getText().equals("")){
            JOptionPane.showMessageDialog(this,
                    "Data invalida!!" ,
                    "Entrada",
                    JOptionPane.ERROR_MESSAGE);
        }else{
            
            controleEntrada.SalvarEntrada(validaValorEntrada, jTextFieldDataEntrada.getText(), jComboBoxContaEntrada.getSelectedItem());
            JOptionPane.showMessageDialog(this,
                    "Entrada adicionada com sucesso!" ,
                    "Entrada",
                    JOptionPane.INFORMATION_MESSAGE);
            adicionaLinhaTabelaEntradas();
            adicionaLinhaTabelaContas();
        }
    }//GEN-LAST:event_jButtonConfirmarEntradaActionPerformed

    private void jComboBoxContaEntradaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxContaEntradaMouseClicked
        jComboBoxContaEntrada.setModel(new DefaultComboBoxModel(controleEntrada.BuscarNomeContas().toArray()));
    }//GEN-LAST:event_jComboBoxContaEntradaMouseClicked

    private void jButtonConfirmarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarContaActionPerformed
        
        double validaValorInicial = Double.parseDouble(jTextFieldValorInicial.getText());
        
        if(jTextFieldNomeConta.getText().equals("")){
            JOptionPane.showMessageDialog(this,
                    "Nome invalido!" ,
                    "Conta",
                    JOptionPane.ERROR_MESSAGE);
        }else if(validaValorInicial < 0){
            JOptionPane.showMessageDialog(this,
                    "Valor invalido!!!!" ,
                    "Conta",
                    JOptionPane.ERROR_MESSAGE);
        }else{
            controleConta.SalvarConta(jTextFieldNomeConta.getText(),validaValorInicial);
            JOptionPane.showMessageDialog(this,
                    "Conta adicionada com sucesso!" ,
                    "Conta",
                    JOptionPane.INFORMATION_MESSAGE);
            
            adicionaLinhaTabelaContas();
        }
        jTextFieldNomeConta.setText("");
        jTextFieldValorInicial.setText("");
    }//GEN-LAST:event_jButtonConfirmarContaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jComboBoxContaSaida.setModel(new DefaultComboBoxModel(controleSaida.BuscarNomeConta().toArray()));
        jComboBoxContaEntrada.setModel(new DefaultComboBoxModel(controleEntrada.BuscarNomeContas().toArray()));
        adicionaLinhaTabelaContas();
        adicionaLinhaTabelaEntradas();
        adicionaLinhaTabelaSaidas();
               
       
    }//GEN-LAST:event_formWindowOpened

    private void jButtonConfirmarSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarSaidaActionPerformed

        double validaValorSaida = Double.parseDouble(jTextFieldValorSaida.getText());

        if(jTextFieldValorSaida.getText().equals("") || validaValorSaida <= 0){
            JOptionPane.showMessageDialog(this,
                "Valor de saida invalido!" ,
                "Saida",
                JOptionPane.ERROR_MESSAGE);
        }else if(jTextFieldDataSaida.getText().equals("")){
            JOptionPane.showMessageDialog(this,
                "Data invalida!!" ,
                "Saida",
                JOptionPane.ERROR_MESSAGE);
        }else{

            controleSaida.SalvarSaida(validaValorSaida, jTextFieldDataSaida.getText(), jComboBoxContaSaida.getSelectedItem());
            JOptionPane.showMessageDialog(this,
                "Saida adicionada com sucesso!" ,
                "Saida",
                JOptionPane.INFORMATION_MESSAGE);

            adicionaLinhaTabelaSaidas();
            adicionaLinhaTabelaContas();
        }
    }//GEN-LAST:event_jButtonConfirmarSaidaActionPerformed

    private void jComboBoxContaSaidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxContaSaidaMouseClicked
        jComboBoxContaSaida.setModel(new DefaultComboBoxModel(controleSaida.BuscarNomeConta().toArray()));
    }//GEN-LAST:event_jComboBoxContaSaidaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConfirmarConta;
    private javax.swing.JButton jButtonConfirmarEntrada;
    private javax.swing.JButton jButtonConfirmarSaida;
    private javax.swing.JComboBox<String> jComboBoxContaEntrada;
    private javax.swing.JComboBox<String> jComboBoxContaSaida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableContas;
    private javax.swing.JTable jTableEntradas;
    private javax.swing.JTable jTableSaidas;
    private javax.swing.JTextField jTextFieldDataEntrada;
    private javax.swing.JTextField jTextFieldDataSaida;
    private javax.swing.JTextField jTextFieldNomeConta;
    private javax.swing.JTextField jTextFieldValorEntrada;
    private javax.swing.JTextField jTextFieldValorInicial;
    private javax.swing.JTextField jTextFieldValorSaida;
    // End of variables declaration//GEN-END:variables
}
